<form action="" class="page-function">
    <div>
        <div>
            <button type="button" onclick="self.location='<?php echo bUrl('editContent')?>'">新增資料</button>
        </div>
    </div>
    <div>
        <input type="text" placeholder="關鍵字">
        <button>搜尋</button>
    </div>
</form>
<form action="" id="page-datalist">
    <table class="page-table align-center">
        <thead>
            <tr>
                <th>社區名稱</th>
                <th>待收款項</th>
                <th>金額</th>
                <th>承辦人員</th>
                <th>建立日期</th>
                <th>收款日期</th>
                <th>操作</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>社區A</td>
                <td>社區管理費用</td>
                <td>1600</td>
                <td>范先生</td>
                <td>2016/05/30</td>
                <td>尚未收款</td>
                <td>
                    <button>編輯</button>
                </td>
            </tr>
             <tr>
                <td>社區A</td>
                <td>社區管理費用</td>
                <td>1600</td>
                <td>范先生</td>
                <td>2016/05/30</td>
                <td>尚未收款</td>
                <td>
                    <button>編輯</button>
                </td>
            </tr>
             <tr>
                <td>社區A</td>
                <td>社區管理費用</td>
                <td>1600</td>
                <td>范先生</td>
                <td>2016/05/30</td>
                <td>尚未收款</td>
                <td>
                    <button>編輯</button>
                </td>
            </tr>
             <tr>
                <td>社區A</td>
                <td>社區管理費用</td>
                <td>1600</td>
                <td>范先生</td>
                <td>2016/05/30</td>
                <td>尚未收款</td>
                <td>
                    <button>編輯</button>
                </td>
            </tr>
        </tbody>
        <tfoot>
            <tr>
                <td colspan="7"></td>
            </tr>
        </tfoot>
    </table>
</form>
